apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-deployment
  namespace: default
  labels:
    app: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka-container
          image: mohamedaitlahcen/eureka-service
          env:
            - name: server.port
              value: '8761'
            - name: eureka.client.fetch-registry
              value: 'false'
            - name: eureka.client.register-with-eureka
              value: 'false'
          ports:
            - containerPort: 8761
