apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: default
  labels:
    run: gateway-service
spec:
  ports:
  - port: 9999
    targetPort: 9999
    protocol: TCP
  type: LoadBalancer
  selector:
    app: gateway