apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: customer-service
  labels:
    run: customer-service
spec:
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
  type: ClusterIP
  selector:
    app: customer