apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  namespace: default
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway-container
          image: mohamedaitlahcen/enset-gateway
          env:
            - name: eureka.instance.prefer-ip-address
              value: 'true'
            - name: server.port
              value: '9999'
            - name: spring.application.name
              value: GATEWAY
            - name: spring.cloud.discovery.enabled
              value: 'true'
            - name: eureka.client.service-url.defaultZone
              value: http://eureka-service:8761/eureka
          ports:
            - containerPort: 9999
