apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: billing-service
  labels:
    run: billing-service
spec:
  ports:
    - port: 8083
      targetPort: 8083
      protocol: TCP
  type: ClusterIP
  selector:
    app: billing