apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  namespace: default
  labels:
    run: eureka-service
spec:
  ports:
    - port: 8761
      targetPort: 8761
      protocol: TCP
  type: LoadBalancer
  selector:
    app: eureka